<<<<<<< HEAD
name: Deploy

on: [push]

jobs:
=======
name: continuos-deployment

on:
  push:
    branches: [main, test]
  pull_request:
    types: [opened, reopened, closed]

jobs:    
>>>>>>> e9ac2f39ccbeca90f64c70dd39defa4448103f7e
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
      - name: Copy repository content to VM
        uses: appleboy/scp-action@master
        with:
          HOST: 146.185.242.115
          USERNAME: ubuntu
          PORT: 22
          sshkey: ${{ secrets.sshkey }}
          source: "."
          target: ~/AdDoBackendDeploy

      - name: Executing remote command
        uses: appleboy/ssh-action@master
=======
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm install
      - name: Compile webpack
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Minio deploy
        uses: mamal72/minio-perfect-deploy-action@main
        with:
          endpoint: https://api.s3.musicon.space/
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'frontend'
          source_dir: 'dist'
          target_dir: '/'
      - name: Copy index.html content to VM
        uses: appleboy/scp-action@v0.1.4
>>>>>>> e9ac2f39ccbeca90f64c70dd39defa4448103f7e
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
<<<<<<< HEAD
          script: cd AdDoBackendDeploy && chmod +x deploy.sh && ./deploy.sh
=======
          source: dist/index.html
          target: /home/musicon/
>>>>>>> e9ac2f39ccbeca90f64c70dd39defa4448103f7e
